// lib/resources.js — Ressources pédagogiques gratuites, programme sénégalais
// 12-15 ressources par matière, organisées par type

export const RESOURCES = {
  mathematiques: [
    { type:"video", title:"Maths BAC Sénégal — DiasporEduc",       url:"https://www.youtube.com/@DiasporEduc",                       desc:"Chaîne dédiée au BAC sénégalais : suites, intégrales, probabilités" },
    { type:"video", title:"Maths Facile — YouTube",                  url:"https://www.youtube.com/results?search_query=maths+bac+senegal+terminale+s", desc:"Corrections d'épreuves BAC Sénégal S et L" },
    { type:"web",   title:"Khan Academy Mathématiques (FR)",          url:"https://fr.khanacademy.org/math",                           desc:"Du primaire au lycée : cours vidéo + exercices interactifs gratuits" },
    { type:"web",   title:"Bibmath.net — Cours & exercices",          url:"https://www.bibmath.net",                                   desc:"Fiches de cours, exercices corrigés, du collège à l'université" },
    { type:"web",   title:"Mathrix — Vidéos pédagogiques",            url:"https://www.youtube.com/@Mathrix",                          desc:"Explications claires du collège au lycée" },
    { type:"video", title:"Révisions BFEM Mathématiques",             url:"https://www.youtube.com/results?search_query=revision+bfem+mathematiques+senegal", desc:"Exercices types BFEM Sénégal" },
    { type:"web",   title:"Exo7 — Cours et exercices PDF gratuits",   url:"http://exo7.emath.fr",                                      desc:"Milliers d'exercices corrigés téléchargeables en PDF" },
    { type:"web",   title:"Sesamath — Manuel interactif",             url:"https://www.sesamath.net",                                  desc:"Manuels numériques gratuits du collège" },
    { type:"video", title:"Prof Shadoko — Maths lycée",               url:"https://www.youtube.com/@profshadoko",                      desc:"Fonctions, dérivées, intégrales expliquées simplement" },
    { type:"web",   title:"MathEnPoche — Exercices interactifs",      url:"https://mathenpoche.sesamath.net",                          desc:"Exercices en ligne adaptés aux niveaux collège" },
    { type:"web",   title:"Annales BAC Sénégal — Maths",              url:"https://www.africaclassroom.com/senegal/bac",               desc:"Annales officielles du BAC sénégalais corrigées" },
    { type:"video", title:"Lumni — Lycée Mathématiques",              url:"https://www.lumni.fr/lycee/terminale/mathematiques",         desc:"Vidéos du service public pour la Terminale" },
    { type:"web",   title:"GeoGebra — Géométrie interactive",         url:"https://www.geogebra.org/calculator",                       desc:"Outil gratuit pour visualiser géométrie, fonctions, statistiques" },
    { type:"web",   title:"Desmos — Calculatrice graphique",          url:"https://www.desmos.com/calculator",                         desc:"Tracé de courbes en ligne, gratuit" },
    { type:"web",   title:"UCAD Département Maths — Ressources",      url:"https://www.ucad.sn",                                       desc:"Université de Dakar — ressources et annales" },
  ],
  physique: [
    { type:"video", title:"PC BAC Sénégal — Terminale S",             url:"https://www.youtube.com/results?search_query=physique+chimie+terminale+bac+senegal+s", desc:"Corrections d'épreuves officielles BAC S Sénégal" },
    { type:"video", title:"Révision Physique BFEM Sénégal",           url:"https://www.youtube.com/results?search_query=physique+bfem+senegal",                    desc:"Exercices types BFEM physique-chimie" },
    { type:"web",   title:"Khan Academy Physique (FR)",                url:"https://fr.khanacademy.org/science/physics",                desc:"Cours complets de mécanique, électricité, optique" },
    { type:"web",   title:"Physique-chimie.fr — Cours lycée",          url:"https://www.physique-chimie.fr",                           desc:"Cours structurés, exercices, seconde à terminale" },
    { type:"video", title:"Yvan Monka — Physique Chimie",              url:"https://www.youtube.com/@yvanmonkaphysiquechimie",           desc:"Milliers de vidéos de PC, toutes notions du lycée" },
    { type:"web",   title:"Futura Sciences — Physique",                url:"https://www.futura-sciences.com/sciences/physique/",        desc:"Articles et dossiers de vulgarisation scientifique" },
    { type:"web",   title:"Edumedia — Animations scientifiques",       url:"https://www.edumedia-sciences.com",                        desc:"Animations 3D interactives : optique, mécanique, circuits" },
    { type:"video", title:"ScienceEtonnante — Vulgarisation",          url:"https://www.youtube.com/@ScienceEtonnante",                 desc:"Physique et chimie expliquées avec enthousiasme" },
    { type:"web",   title:"Chimie-Organique.fr",                       url:"https://www.chimie-organique.net",                         desc:"Cours de chimie organique pour Terminale S" },
    { type:"web",   title:"Maxicours — Physique-Chimie",               url:"https://www.maxicours.com/se/matiere/physique-chimie/",     desc:"Fiches de cours et exercices corrigés de la 6e à la Terminale" },
    { type:"video", title:"Mr Saby — Physique Terminale",              url:"https://www.youtube.com/results?search_query=Mr+saby+physique+terminale", desc:"Cours de thermodynamique, mécanique, ondes" },
    { type:"web",   title:"Annales BAC S Physique — Sénégal",          url:"https://www.africaclassroom.com/senegal/bac/physique",      desc:"Annales officielles avec corrections" },
    { type:"web",   title:"Périodic Table — Tableau périodique",       url:"https://www.ptable.com/?lang=fr",                          desc:"Tableau périodique interactif en français" },
    { type:"video", title:"Le Labo de Physique",                       url:"https://www.youtube.com/@lelabodephysique",                 desc:"Expériences et démonstrations de physique" },
  ],
  svt: [
    { type:"video", title:"SVT BAC Sénégal — Terminale S",            url:"https://www.youtube.com/results?search_query=svt+bac+terminale+senegal", desc:"Corrections d'épreuves BAC SVT Sénégal" },
    { type:"web",   title:"Khan Academy Biologie (FR)",                url:"https://fr.khanacademy.org/science/biology",                desc:"Génétique, cellule, évolution — cours vidéo complets" },
    { type:"web",   title:"SVT-Cours.fr — Fiches lycée",               url:"https://www.svt-cours.fr",                                 desc:"Cours complets de SVT du lycée, fiches téléchargeables" },
    { type:"video", title:"Le Monde des Cellules — YouTube",           url:"https://www.youtube.com/results?search_query=svt+lycee+genetique+immunologie", desc:"Génétique, immunologie, neurologie expliqués" },
    { type:"web",   title:"Futura Santé — Biologie humaine",           url:"https://www.futura-sciences.com/sante/",                   desc:"Corps humain, maladies, génétique vulgarisés" },
    { type:"video", title:"SVT Révisions BFEM Sénégal",               url:"https://www.youtube.com/results?search_query=svt+bfem+senegal+revision",  desc:"Exercices types BFEM — SVT" },
    { type:"web",   title:"INRB Sénégal — Ressources biologiques",     url:"https://www.isra.sn",                                      desc:"Institut sénégalais de recherches agricoles — biodiversité locale" },
    { type:"web",   title:"Maxicours — SVT",                           url:"https://www.maxicours.com/se/matiere/svt/",                 desc:"Cours, exercices et quiz de SVT collège et lycée" },
    { type:"video", title:"Dirty Biology — Vulgarisation",             url:"https://www.youtube.com/@dirtybiology",                    desc:"Biologie et écologie en vidéos engageantes" },
    { type:"web",   title:"Acces.EduNation — SVT Afrique",             url:"https://www.lumni.fr/lycee/premiere/svt",                  desc:"Vidéos SVT adaptées au programme africain" },
    { type:"web",   title:"SVT en Ligne — Cours interactifs",          url:"https://www.svtenligne.fr",                                desc:"Cours illustrés, animations, quiz SVT" },
    { type:"video", title:"Sciences de la Vie — 5 Leçons",            url:"https://www.youtube.com/results?search_query=genetique+moleculaire+bac+svt", desc:"ADN, ARN, synthèse des protéines expliqués" },
    { type:"web",   title:"Atlas de l'Environnement Sénégal",          url:"https://www.iucn.org/africa/senegal",                      desc:"Biodiversité et environnement au Sénégal" },
  ],
  francais: [
    { type:"video", title:"Français BAC Sénégal — Dissertation",       url:"https://www.youtube.com/results?search_query=dissertation+francais+bac+senegal", desc:"Méthode dissertation et commentaire composé BAC" },
    { type:"web",   title:"Lumni — Français Lycée",                    url:"https://www.lumni.fr/lycee/premiere/francais",              desc:"Vidéos pédagogiques Première et Terminale" },
    { type:"web",   title:"Alloprof — Français complet",               url:"https://www.alloprof.qc.ca/fr/eleves/bv/francais",          desc:"Grammaire, conjugaison, types de textes, analyse" },
    { type:"video", title:"Le Précepteur — Méthode Bac",               url:"https://www.youtube.com/@leprecepteur",                     desc:"Méthode commentaire composé et dissertation niveau BAC" },
    { type:"web",   title:"Bescherelle en ligne",                       url:"https://bescherelle.com",                                  desc:"Conjugaison complète de tous les verbes français" },
    { type:"video", title:"Révisions BFEM Français Sénégal",           url:"https://www.youtube.com/results?search_query=bfem+francais+senegal+grammaire", desc:"Grammaire, expression écrite BFEM" },
    { type:"web",   title:"TV5Monde — Exercices de langue",             url:"https://langue-francaise.tv5monde.com",                    desc:"Exercices de compréhension et expression française" },
    { type:"web",   title:"Littérature Africaine — Île en Île",        url:"https://www.lehman.edu/ile.en.ile/",                        desc:"Auteurs africains francophones : Senghor, Sembène, etc." },
    { type:"video", title:"Senghor et la Négritude — Cours",           url:"https://www.youtube.com/results?search_query=senghor+negritude+litterature+africaine", desc:"Littérature sénégalaise au programme" },
    { type:"web",   title:"Projet Voltaire — Orthographe",             url:"https://www.projet-voltaire.fr",                           desc:"Exercices d'orthographe et grammaire en ligne" },
    { type:"web",   title:"Annales BAC Français Sénégal",              url:"https://www.africaclassroom.com/senegal/bac/francais",      desc:"Annales et corrigés officiels" },
    { type:"video", title:"Expressions Sénégalaises — Culture",        url:"https://www.youtube.com/results?search_query=litterature+senegalaise+cours",         desc:"Littérature sénégalaise contemporaine" },
    { type:"web",   title:"Ortholud — Jeux de grammaire",              url:"https://www.ortholud.com",                                 desc:"Jeux éducatifs de conjugaison et orthographe" },
  ],
  histoire: [
    { type:"video", title:"Histoire-Géo BAC Sénégal",                  url:"https://www.youtube.com/results?search_query=histoire+geographie+bac+senegal+terminale", desc:"Révisions BAC Histoire-Géo programme sénégalais" },
    { type:"web",   title:"Lumni — Histoire-Géographie Lycée",         url:"https://www.lumni.fr/lycee/terminale/histoire-geographie",  desc:"Documentaires et vidéos pédagogiques" },
    { type:"video", title:"Révisions BFEM Histoire-Géo",               url:"https://www.youtube.com/results?search_query=bfem+histoire+geographie+senegal",        desc:"Programme BFEM Histoire-Géo complet" },
    { type:"web",   title:"Alloprof — Histoire",                       url:"https://www.alloprof.qc.ca/fr/eleves/bv/histoire",          desc:"Fiches de cours, chronologies, cartes" },
    { type:"web",   title:"Monde Diplomatique — Géopolitique",         url:"https://www.monde-diplomatique.fr",                        desc:"Analyses géopolitiques contemporaines" },
    { type:"video", title:"AfriquHistoire — YouTube",                  url:"https://www.youtube.com/@afriquehistoire",                  desc:"Histoire de l'Afrique : empires, colonisation, indépendances" },
    { type:"web",   title:"Encyclopédie Universalis — Sénégal",        url:"https://www.universalis.fr/encyclopedie/senegal/",          desc:"Histoire complète du Sénégal" },
    { type:"video", title:"La Géographie — YouTube",                   url:"https://www.youtube.com/results?search_query=geographie+afrique+cours+lycee",          desc:"Géographie de l'Afrique et du monde" },
    { type:"web",   title:"Nations Online — Cartes du Sénégal",        url:"https://www.nationsonline.org/oneworld/senegal.htm",         desc:"Cartes, géographie, données statistiques du Sénégal" },
    { type:"web",   title:"Géoportail Sénégal",                        url:"https://www.geoportail.sn",                                desc:"Cartographie officielle du Sénégal" },
    { type:"web",   title:"Annales BAC Histoire-Géo Sénégal",          url:"https://www.africaclassroom.com/senegal/bac/histoire",      desc:"Annales et corrigés officiels BAC" },
    { type:"video", title:"Chroniques de l'Afrique — ARTE",            url:"https://www.youtube.com/results?search_query=histoire+afrique+arte+documentaire",     desc:"Documentaires ARTE sur l'histoire africaine" },
    { type:"web",   title:"Perspective Monde — Statistiques",          url:"https://perspective.usherbrooke.ca",                       desc:"Données économiques et sociales par pays (cartes, graphes)" },
  ],
  anglais: [
    { type:"web",   title:"BBC Learning English",                      url:"https://www.bbc.co.uk/learningenglish",                     desc:"Cours audio/vidéo gratuits, tous niveaux — BBC officiel" },
    { type:"web",   title:"British Council LearnEnglish",              url:"https://learnenglish.britishcouncil.org",                   desc:"Grammaire, vocabulaire, compréhension orale et écrite" },
    { type:"video", title:"Anglais BAC Sénégal — YouTube",             url:"https://www.youtube.com/results?search_query=anglais+bac+bfem+senegal+revision",      desc:"Révisions BAC et BFEM, méthode et vocabulary" },
    { type:"web",   title:"Duolingo — Anglais",                        url:"https://www.duolingo.com",                                 desc:"Apprentissage ludique et progressif, 15 min/jour" },
    { type:"web",   title:"Cambridge English — Ressources gratuites",  url:"https://www.cambridgeenglish.org/learning-english/",        desc:"Exercices de grammaire et vocabulaire, tests" },
    { type:"video", title:"English with Lucy — YouTube",               url:"https://www.youtube.com/@EnglishwithLucy",                  desc:"Prononciation, grammaire et vocabulaire avancé" },
    { type:"web",   title:"Lyrics Training — Apprendre avec la musique",url:"https://lyricstraining.com",                              desc:"Apprentissage de l'anglais via les paroles de chansons" },
    { type:"web",   title:"Vocabulary.com",                            url:"https://www.vocabulary.com",                               desc:"Apprentissage de vocabulaire anglais, adaptatif" },
    { type:"video", title:"TED-Ed — Conférences en anglais",           url:"https://ed.ted.com",                                       desc:"Vidéos éducatives en anglais sur tous les sujets" },
    { type:"web",   title:"English Grammar in Use — Exercices",        url:"https://www.englishgrammar.org",                           desc:"Exercices de grammaire anglaise, tous niveaux" },
    { type:"web",   title:"Annales BAC Anglais Sénégal",               url:"https://www.africaclassroom.com/senegal/bac/anglais",       desc:"Annales et corrigés officiels BAC Anglais" },
    { type:"video", title:"Africa English Learning — YouTube",         url:"https://www.youtube.com/results?search_query=english+learning+west+africa+senegal",   desc:"Cours d'anglais adaptés au contexte africain" },
    { type:"web",   title:"EngVid — Vidéos de grammaire",              url:"https://www.engvid.com",                                   desc:"Leçons vidéo de grammaire et vocabulaire anglais" },
  ],
  philosophie: [
    { type:"web",   title:"Philocours — Cours complets",               url:"https://www.philocours.com",                               desc:"Cours, fiches de notions, dissertations modèles" },
    { type:"video", title:"Philo BAC Sénégal — YouTube",               url:"https://www.youtube.com/results?search_query=philosophie+bac+terminale+senegal",      desc:"Cours et corrections BAC philo programme sénégalais" },
    { type:"web",   title:"Philo52 — Cours de terminale",              url:"https://philo52.com",                                      desc:"Toutes les notions du programme de Terminale" },
    { type:"video", title:"François Jourde — YouTube",                 url:"https://www.youtube.com/@francoisjourde",                   desc:"Cours de philosophie, méthode dissertation et notions" },
    { type:"web",   title:"Lumni — Philosophie Terminale",             url:"https://www.lumni.fr/lycee/terminale/philosophie",          desc:"Vidéos pédagogiques sur les grandes notions" },
    { type:"video", title:"Passe Ta Philo — YouTube",                  url:"https://www.youtube.com/results?search_query=passe+ta+philo",                         desc:"Résumés de notions et méthodes pour le BAC" },
    { type:"web",   title:"La Philo en Vidéo",                         url:"https://www.laphiloenvideo.com",                           desc:"Auteurs philosophiques expliqués en vidéo" },
    { type:"web",   title:"Textes de Philosophes — Wikisource",        url:"https://fr.wikisource.org/wiki/Philosophie",               desc:"Textes originaux des grands philosophes, gratuits" },
    { type:"web",   title:"Annales BAC Philosophie Sénégal",           url:"https://www.africaclassroom.com/senegal/bac/philosophie",   desc:"Sujets et corrigés du BAC sénégalais" },
    { type:"video", title:"Monsieur Phi — Philosophie",                url:"https://www.youtube.com/@MonsieurPhi",                     desc:"Philosophie analytique et logique en vidéos claires" },
    { type:"web",   title:"Fiches de Lecture — Résumés",               url:"https://www.fichesdelecturegratuites.com",                 desc:"Résumés d'œuvres philosophiques au programme" },
    { type:"video", title:"Philosophie Africaine — YouTube",           url:"https://www.youtube.com/results?search_query=philosophie+africaine+ubuntu+senghor",   desc:"Philosophie africaine et penseurs du Sénégal" },
  ],
  informatique: [
    { type:"web",   title:"France-IOI — Algorithmique",                url:"https://www.france-ioi.org",                               desc:"Initiation à la programmation, algorithmique, concours" },
    { type:"web",   title:"OpenClassrooms — Python complet",           url:"https://openclassrooms.com/fr/courses/7168871-apprenez-les-bases-du-langage-python", desc:"Cours Python gratuit, du débutant à l'intermédiaire" },
    { type:"video", title:"Informatique NSI — YouTube",                url:"https://www.youtube.com/results?search_query=nsi+terminale+python+algorithmique",    desc:"Cours NSI : Python, bases de données, réseaux" },
    { type:"web",   title:"W3Schools — HTML/CSS/SQL/Python",           url:"https://www.w3schools.com",                                desc:"Référence interactive : code, quiz, exemples en direct" },
    { type:"web",   title:"FreeCodeCamp — Développement Web",          url:"https://www.freecodecamp.org/learn",                       desc:"Cours gratuits HTML, CSS, JavaScript, Python" },
    { type:"web",   title:"Scratch — Programmation visuelle",          url:"https://scratch.mit.edu",                                  desc:"Initiation à la programmation par blocs (collège)" },
    { type:"video", title:"Graven — Python débutant",                  url:"https://www.youtube.com/@Gravenilvectuto",                  desc:"Tutoriels Python pour débutants en français" },
    { type:"web",   title:"SQLZoo — Bases de données SQL",             url:"https://sqlzoo.net",                                       desc:"Apprendre SQL de façon interactive et gratuite" },
    { type:"web",   title:"Cryptoclub — Cryptographie",                url:"https://www.cryptoclub.org",                               desc:"Introduction à la cryptographie pour lycéens" },
    { type:"video", title:"Cours IA & Machine Learning",               url:"https://www.youtube.com/results?search_query=intelligence+artificielle+debutant+francais", desc:"Introduction à l'IA en français" },
    { type:"web",   title:"GitHub Education — Outils gratuits",        url:"https://education.github.com",                             desc:"Outils de développement gratuits pour étudiants" },
    { type:"web",   title:"Annales BAC NSI Informatique",              url:"https://www.africaclassroom.com",                          desc:"Annales et ressources informatique lycée Sénégal" },
  ],
  mathematiques_primaire: [],
  sciences: [
    { type:"web",   title:"La Main à la Pâte — Sciences primaire",     url:"https://www.lamap.fr",                                     desc:"Sciences à l'école primaire, expériences simples" },
    { type:"video", title:"C'est Pas Sorcier — Sciences",              url:"https://www.youtube.com/@cestpassorcier",                   desc:"Émission de vulgarisation scientifique pour enfants" },
    { type:"web",   title:"Lumni — Sciences Primaire",                 url:"https://www.lumni.fr/primaire/sciences",                    desc:"Vidéos scientifiques pour élèves du primaire" },
    { type:"video", title:"Sciences & Vie Junior — YouTube",           url:"https://www.youtube.com/results?search_query=sciences+nature+primaire+enfants+experience", desc:"Expériences et découvertes scientifiques" },
    { type:"web",   title:"Aide aux devoirs — Sciences CM1/CM2",       url:"https://www.aideauxdevoirs.fr",                            desc:"Cours de sciences du programme primaire sénégalais" },
    { type:"web",   title:"Diapason — Sciences CM",                    url:"https://www.education.gouv.sn",                            desc:"Ministère de l'Éducation du Sénégal — ressources primaire" },
    { type:"video", title:"Géographie du Sénégal — Primaire",          url:"https://www.youtube.com/results?search_query=geographie+senegal+primaire+fleuve+region", desc:"Les régions, fleuves et géographie du Sénégal" },
    { type:"web",   title:"Vikidia — Encyclopédie pour enfants",        url:"https://fr.vikidia.org",                                   desc:"Encyclopédie adaptée aux 8-13 ans" },
    { type:"web",   title:"Espace des Sciences — Pour les jeunes",     url:"https://www.espace-sciences.org/jeunes",                   desc:"Articles de sciences accessibles aux jeunes" },
    { type:"video", title:"1 Jour, 1 Question — Sciences",             url:"https://www.youtube.com/@1jour1actu_officiel",              desc:"Questions scientifiques expliquées simplement" },
  ],
  emc: [
    { type:"web",   title:"UNICEF Sénégal — Droits de l'enfant",       url:"https://www.unicef.org/senegal",                           desc:"Droits et protection de l'enfant au Sénégal" },
    { type:"video", title:"Éducation Civique Sénégal — YouTube",       url:"https://www.youtube.com/results?search_query=education+civique+senegal+citoyennete",  desc:"Cours d'éducation civique programme sénégalais" },
    { type:"web",   title:"Institutions du Sénégal — Gouvernement",    url:"https://www.sec.gouv.sn",                                  desc:"Secrétariat d'État — institutions officielles" },
    { type:"web",   title:"Assemblée Nationale du Sénégal",            url:"https://www.assemblee-nationale.sn",                       desc:"Fonctionnement de l'Assemblée nationale" },
    { type:"web",   title:"Commission Nationale des Droits Humains",   url:"https://www.cndh.sn",                                      desc:"Droits humains et libertés fondamentales au Sénégal" },
    { type:"video", title:"Démocratie et Citoyenneté — YouTube",       url:"https://www.youtube.com/results?search_query=democratie+citoyennete+afrique+senegal",  desc:"Valeurs démocratiques et citoyenneté africaine" },
    { type:"web",   title:"Lumni — EMC & Morale",                      url:"https://www.lumni.fr/primaire/moral-et-civique",            desc:"Vidéos sur le respect, la solidarité, le vivre ensemble" },
    { type:"web",   title:"Plan Sénégal Émergent — PSE",               url:"https://www.senegal-emergent.com",                         desc:"Développement et enjeux du Sénégal contemporain" },
  ],
  eco: [
    { type:"video", title:"Économie BAC STEG Sénégal",                 url:"https://www.youtube.com/results?search_query=economie+steg+bac+senegal+revision",     desc:"Révisions complètes BAC STEG Économie" },
    { type:"web",   title:"Alternatives Économiques",                  url:"https://www.alternatives-economiques.fr",                  desc:"Articles et dossiers d'économie accessibles" },
    { type:"web",   title:"Khan Academy Économie et Finance",          url:"https://fr.khanacademy.org/economics-finance-domain",      desc:"Microéconomie, macroéconomie, finance personnelle" },
    { type:"web",   title:"BCEAO — Banque Centrale Afrique de l'Ouest",url:"https://www.bceao.int",                                    desc:"Données économiques de la zone UEMOA, Sénégal" },
    { type:"web",   title:"ANSD — Statistiques Sénégal",               url:"https://www.ansd.sn",                                      desc:"Agence Nationale de la Statistique et de la Démographie" },
    { type:"video", title:"Heu?reka — Économie vulgarisée",            url:"https://www.youtube.com/@Heu7reka",                        desc:"Économie et finance expliquées simplement" },
    { type:"web",   title:"Vie Publique — Économie française et mondiale",url:"https://www.vie-publique.fr/catalogue/economie",        desc:"Dossiers sur les grandes questions économiques" },
    { type:"web",   title:"Annales BAC STEG Sénégal",                  url:"https://www.africaclassroom.com/senegal/bac/steg",          desc:"Sujets et corrigés BAC STEG officiels" },
    { type:"video", title:"Gestion d'Entreprise — YouTube",            url:"https://www.youtube.com/results?search_query=gestion+entreprise+comptabilite+lycee",   desc:"Comptabilité générale et gestion lycée" },
    { type:"web",   title:"Cours de Comptabilité Gratuits",            url:"https://www.compta-facile.com",                            desc:"Comptabilité générale expliquée étape par étape" },
    { type:"web",   title:"OCDE — Perspectives Afrique",               url:"https://www.oecd.org/fr/dev/afrique.htm",                  desc:"Rapports économiques sur l'Afrique subsaharienne" },
  ],
};
